# Generated by Django 3.2.8 on 2022-06-15 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_emp_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_empresa', models.CharField(max_length=5, verbose_name='Nombre Empresa')),
                ('raz_empresa', models.CharField(max_length=5, verbose_name='Razón Social Empresa')),
                ('nit_empresa', models.CharField(max_length=5, verbose_name='Nit Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_eva_pk', models.AutoField(primary_key=True, serialize=False)),
                ('eva_descripcion', models.CharField(max_length=5, verbose_name='Evaluación Descripción')),
                ('eva_calificacion', models.IntegerField(verbose_name='Numeral')),
                ('eva_criterio', models.CharField(max_length=5, verbose_name='Evaluación Criterio')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item_pk', models.AutoField(primary_key=True, serialize=False)),
                ('num_item', models.FloatField(verbose_name='Numeral')),
                ('nomb_item', models.CharField(max_length=120, verbose_name='Nombre Item')),
            ],
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id_nor_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nor', models.CharField(max_length=60, verbose_name='Norma')),
                ('des_nor', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id_req_pk', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_req', models.CharField(max_length=5, verbose_name='Nombre')),
                ('descrip_req', models.TextField(max_length=255, verbose_name='Descripción')),
                ('nota_req', models.CharField(max_length=255, verbose_name='Nota')),
                ('infdoc_req', models.CharField(max_length=255, verbose_name='Información Documentada')),
                ('cambios_req', models.CharField(max_length=255, verbose_name='Cambios')),
                ('infdoc_exist_req', models.CharField(max_length=255, verbose_name='Informacion Doc Existente')),
                ('infdoc_falta_req', models.CharField(max_length=255, verbose_name='Informacion Doc Faltante')),
                ('esqcumplact_req', models.CharField(max_length=255, verbose_name='Esquema Cumplimiento Actual')),
                ('infdoc_elab_req', models.CharField(max_length=255, verbose_name='Información Doc a Elaborar')),
                ('actrealizar_req', models.CharField(max_length=255, verbose_name='Información Doc a Elaborar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id_pun_pk', models.AutoField(primary_key=True, serialize=False)),
                ('num_pun', models.IntegerField(verbose_name='Numeral')),
                ('nomb_pun', models.CharField(max_length=60, verbose_name='Nombre')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.norma')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='punto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.punto'),
        ),
        migrations.CreateModel(
            name='EvaReqEmpresa',
            fields=[
                ('id_eva_req_emp_pk', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.empresa')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.evaluacion')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.requisito')),
            ],
        ),
    ]
