# Generated by Django 3.2.8 on 2022-06-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20220614_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['id_emp_pk'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id_item_pk'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='norma',
            options={'ordering': ['id_nor_pk'], 'verbose_name': 'Norma', 'verbose_name_plural': 'Normas'},
        ),
        migrations.AlterModelOptions(
            name='punto',
            options={'ordering': ['id_pun_pk'], 'verbose_name': 'Punto', 'verbose_name_plural': 'Puntos'},
        ),
        migrations.AlterModelOptions(
            name='requisito',
            options={'ordering': ['id_req_pk'], 'verbose_name': 'Requisito', 'verbose_name_plural': 'Requisitos'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit_empresa',
            field=models.CharField(max_length=15, verbose_name='Nit Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nomb_empresa',
            field=models.CharField(max_length=150, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='raz_empresa',
            field=models.CharField(max_length=250, verbose_name='Razón Social Empresa'),
        ),
        migrations.AlterField(
            model_name='norma',
            name='nor',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
    ]
